#!/bin/bash
aws s3api copy-object --bucket SNR-bucket --key deepSNR01.mat --copy-source my-bucket-test/deepSNR01.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR02.mat --copy-source my-bucket-test/deepSNR02.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR03.mat --copy-source my-bucket-test/deepSNR03.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR04.mat --copy-source my-bucket-test/deepSNR04.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR05.mat --copy-source my-bucket-test/deepSNR05.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR06.mat --copy-source my-bucket-test/deepSNR06.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR07.mat --copy-source my-bucket-test/deepSNR07.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR08.mat --copy-source my-bucket-test/deepSNR08.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR09.mat --copy-source my-bucket-test/deepSNR09.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR10.mat --copy-source my-bucket-test/deepSNR10.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR11.mat --copy-source my-bucket-test/deepSNR11.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR12.mat --copy-source my-bucket-test/deepSNR12.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR13.mat --copy-source my-bucket-test/deepSNR13.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR14.mat --copy-source my-bucket-test/deepSNR14.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR15.mat --copy-source my-bucket-test/deepSNR15.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR16.mat --copy-source my-bucket-test/deepSNR16.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR17.mat --copy-source my-bucket-test/deepSNR17.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR18.mat --copy-source my-bucket-test/deepSNR18.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR19.mat --copy-source my-bucket-test/deepSNR19.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR20.mat --copy-source my-bucket-test/deepSNR20.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR21.mat --copy-source my-bucket-test/deepSNR21.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR22.mat --copy-source my-bucket-test/deepSNR22.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR23.mat --copy-source my-bucket-test/deepSNR23.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR24.mat --copy-source my-bucket-test/deepSNR24.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR25.mat --copy-source my-bucket-test/deepSNR25.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR26.mat --copy-source my-bucket-test/deepSNR26.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR27.mat --copy-source my-bucket-test/deepSNR27.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR28.mat --copy-source my-bucket-test/deepSNR28.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR29.mat --copy-source my-bucket-test/deepSNR29.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR30.mat --copy-source my-bucket-test/deepSNR30.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR31.mat --copy-source my-bucket-test/deepSNR31.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR32.mat --copy-source my-bucket-test/deepSNR32.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR33.mat --copy-source my-bucket-test/deepSNR33.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR34.mat --copy-source my-bucket-test/deepSNR34.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR35.mat --copy-source my-bucket-test/deepSNR35.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR36.mat --copy-source my-bucket-test/deepSNR36.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR37.mat --copy-source my-bucket-test/deepSNR37.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR38.mat --copy-source my-bucket-test/deepSNR38.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR39.mat --copy-source my-bucket-test/deepSNR39.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api copy-object --bucket SNR-bucket --key deepSNR40.mat --copy-source my-bucket-test/deepSNR40.mat --endpoint-url https://s3-west.nrp-nautilus.io
aws s3api list-objects --bucket SNR-bucket  --endpoint-url https://s3-west.nrp-nautilus.io
