FROM tensorflow/tensorflow:latest-gpu

ADD deep_nnEq.py deepSNR25.mat /

RUN apt-get update && apt-get install -y \
    python3-pip \
    vim && \
    pip3 install numpy scipy pandas

CMD [ "python", "deep_nnEq.py"]
